# Generated by Django 5.1.1 on 2025-04-15 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('manf_yr', models.DateField()),
                ('colour', models.CharField(max_length=25)),
                ('engine_type', models.CharField(max_length=10)),
                ('Description', models.TextField(max_length=250)),
                ('accessed_username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yamaha.user_list')),
            ],
        ),
    ]
