# Generated by Django 5.1.1 on 2025-05-16 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0002_alter_variants_accessed_username_delete_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variants',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
