# Generated by Django 5.1.1 on 2025-05-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0003_variants_modified_date_alter_variants_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
