# Generated by Django 5.1.1 on 2025-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='variants',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
