# Generated by Django 5.1.1 on 2025-05-24 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0007_alter_variants_accessed_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
