# Generated by Django 5.1.1 on 2025-06-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0009_role_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
