# Generated by Django 5.1.1 on 2025-06-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0011_registration_username_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='accessed_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamaha.registration'),
        ),
    ]
