# Generated by Django 5.1.1 on 2025-06-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0013_alter_variants_accessed_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yamaha.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
