# Generated by Django 5.1.1 on 2025-06-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0014_alter_registration_role_alter_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='accessed_username',
        ),
    ]
