# Generated by Django 5.1.1 on 2025-06-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamaha', '0015_remove_variants_accessed_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='accessed_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yamaha.registration'),
        ),
    ]
